name: Publish Single File

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        default: "v1.2.0"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Building-GUI:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build FMOD-Decompiler.sln --no-restore

    - name: Publish FMOD-Decompiler
      run: dotnet publish FMOD-Decompiler.sln -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true --output ./publish

    - name: Copy README and LICENSE Files
      run: |
        copy README.md publish\
        copy LICENSE.txt publish\

    - name: Create ZIP from Build
      run: |
        7z a -tzip FMOD-Decompiler-${{ github.event.inputs.version }}.zip ./publish/* -mx0

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        body: |
          This is release ${{ github.event.inputs.version }} of FMOD-Decompiler
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: FMOD-Decompiler-${{ github.event.inputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
